name: cyclone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_otp_text_field: ^1.1.1
  get: ^4.6.6
  google_fonts: ^6.1.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#fcfcfc"
  color_dark: "#272727"
  image: assets/images/splash_images/cocycle2.png
  image_dark: assets/images/splash_images/cocycle2.png
  web: true

  android_12:
    image: assets/images/splash_images/cocycle2.png
    icon_background_color: "#fcfcfc"
    image_dark: assets/images/splash_images/cocycle2.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/splash_images/
   - assets/images/on_boarding_images/
   - assets/images/welcome_images/
   - assets/logo/
   - assets/images/forget_password/
