name: cyclone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

  ## -- SPLASHSCREEN PACKAGE
  flutter_native_splash: ^2.3.4

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.6
  line_awesome_flutter: ^2.0.0

  ## -- FIREBASE PACKAGES
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1


  ## -- OTP FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FROM FIELD PACKAGES
  intl_phone_number_field: ^0.1.8
  image_picker: ^1.0.4
  
  ## -- STATE MANAGEMENT PACKAGES
  get: ^4.6.6

  ## -- ONBOARDING PACKAGES
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.0
  uuid: ^4.2.2
  flutter_riverpod: ^2.4.9
  video_player: ^2.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

## -- SPLASHSCREEN CONFIG
flutter_native_splash:
  color: "#fcfcfc"
  color_dark: "#272727"
  image: assets/images/splash_images/cocycle2.png
  image_dark: assets/images/splash_images/cocycle2.png
  web: true

  android_12:
    image: assets/images/splash_images/cocycle2.png
    icon_background_color: "#fcfcfc"
    image_dark: assets/images/splash_images/cocycle2.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/images/splash_images/
   - assets/images/on_boarding_images/
   - assets/images/welcome_images/
   - assets/logo/
   - assets/images/forget_password/
   - assets/images/homepage/
