// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkDTIWGuDOcIw-mbZ1UHcuYhLoVxYh_yI',
    appId: '1:266399099148:web:27f2b09ea52e2e1e910129',
    messagingSenderId: '266399099148',
    projectId: 'cocycle-bc37b',
    authDomain: 'cocycle-bc37b.firebaseapp.com',
    storageBucket: 'cocycle-bc37b.appspot.com',
    measurementId: 'G-78QKFTYQJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyX-ZaC6LjPwRMV5fffAfmf95HB4Zgb5Q',
    appId: '1:266399099148:android:d3642e85e07ae189910129',
    messagingSenderId: '266399099148',
    projectId: 'cocycle-bc37b',
    storageBucket: 'cocycle-bc37b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrQmTj97BjwxyCMKk0vyIKY1Joknq0BQ',
    appId: '1:266399099148:ios:26d65dea8f42e9c0910129',
    messagingSenderId: '266399099148',
    projectId: 'cocycle-bc37b',
    storageBucket: 'cocycle-bc37b.appspot.com',
    iosBundleId: 'com.example.cyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrQmTj97BjwxyCMKk0vyIKY1Joknq0BQ',
    appId: '1:266399099148:ios:12b46b3ac51420b4910129',
    messagingSenderId: '266399099148',
    projectId: 'cocycle-bc37b',
    storageBucket: 'cocycle-bc37b.appspot.com',
    iosBundleId: 'com.example.cyclone.RunnerTests',
  );
}
